<?php
	switch ($_GET['act']) {
		case 'login':
			if($_GET['mod']=="changePassword"){
				include("modules/login/changePassword.php");
			}
			else if($_GET['mod']=="logout"){
				include("modules/login/logout.php");
			}
			break;
		case 'faculty':
			if($_GET['mod']=="add"){
				include("modules/faculty/add.php");
			}
			elseif($_GET['mod']=="edit"){
				include("modules/faculty/edit.php");
			}
			elseif($_GET['mod']=="delete"){
				include("modules/faculty/delete.php");
			}
			else{
				include("modules/faculty/list.php");
			}
			break;
		case 'doan':
			if($_GET['mod']=="xoa"){
				include("modules/doan/xoa.php");
			}
			elseif($_GET['mod']=="duyetdoan"){
				include("modules/doan/duyetdoan.php");
			}
			elseif($_GET['mod']=="xemtomtat"){
				include("modules/doan/xemtomtat.php");
			}
			else{
				include("modules/doan/danhsach.php");
			}
			break;
		case 'admin':
			if($_GET['mod']=="add"){
				include("modules/admin/add.php");
			}
			elseif($_GET['mod']=="edit"){
				include("modules/admin/edit.php");
			}
			elseif($_GET['mod']=="delete"){
				include("modules/admin/delete.php");
			}
			else{
				include("modules/admin/list.php");
			}
			break;
		case 'hedaotao':
			if($_GET['mod']=="add"){
				include("modules/hedaotao/add.php");
			}
			elseif($_GET['mod']=="sua"){
				include("modules/hedaotao/sua.php");
			}
			elseif($_GET['mod']=="xoa"){
				include("modules/hedaotao/xoa.php");
			}
			else{	
				include("modules/hedaotao/danhsach.php");
			}
			break;
		case 'khoahoc':
			if($_GET['mod']=="them"){
				include("modules/khoahoc/them.php");
			}
			elseif($_GET['mod']=="sua"){
				include("modules/khoahoc/sua.php");
			}
			elseif($_GET['mod']=="xoa"){
				include("modules/khoahoc/xoa.php");
			}
			else{	
				include("modules/khoahoc/danhsach.php");
			}
			break;
		case 'lophoc':
			if($_GET['mod']=="them"){
				include("modules/lophoc/them.php");
			}
			elseif($_GET['mod']=="sua"){
				include("modules/lophoc/sua.php");
			}
			elseif($_GET['mod']=="xoa"){
				include("modules/lophoc/xoa.php");
			}
			else{	
				include("modules/lophoc/danhsach.php");
			}
			break;
		case 'nhomdoan':
			if($_GET['mod']=="them"){
				include("modules/nhomdoan/them.php");
			}
			elseif($_GET['mod']=="sua"){
				include("modules/nhomdoan/sua.php");
			}
			elseif($_GET['mod']=="xoa"){
				include("modules/nhomdoan/xoa.php");
			}
			else{	
				include("modules/nhomdoan/danhsach.php");
			}
			break;
		case 'student':
			if($_GET['mod']=="add"){
				include("modules/student/add.php");
			}
			elseif($_GET['mod']=="edit"){
				include("modules/student/edit.php");
			}
			elseif($_GET['mod']=="delete"){
				include("modules/student/delete.php");
			}
			else{	
				include("modules/student/list.php");
			}
			break;
		case 'nhomtailieu':
			if($_GET['mod']=="them"){
				include("modules/nhomtailieu/them.php");
			}
			elseif($_GET['mod']=="sua"){
				include("modules/nhomtailieu/sua.php");
			}
			elseif($_GET['mod']=="xoa"){
				include("modules/nhomtailieu/xoa.php");
			}
			else{	
				include("modules/nhomtailieu/danhsach.php");
			}
			break;
		case 'tailieu':
			if($_GET['mod']=="them"){
				include("modules/tailieu/them.php");
			}
			elseif($_GET['mod']=="sua"){
				include("modules/tailieu/sua.php");
			}
			elseif($_GET['mod']=="xoa"){
				include("modules/tailieu/xoa.php");
			}
			else{	
				include("modules/tailieu/danhsach.php");
			}
			break;
		default:
			echo "<br/><center><b>WELCOME YOU LOGIN TO THE SYSTEM</b></center></br>";
			break;
	}
?>