<?php
	if($_POST['login']=="login"){
		include("modules/login/functionLogin.php");
	}
	if($_POST['changePassword']=="changePassword"){
		include("modules/login/functionChangePassword.php");
	}
	if($_POST['addFaculty']=="addFaculty"){
		include("modules/faculty/functionAdd.php");
	}
	if($_POST['editFaculty']=="editFaculty"){
		include("modules/faculty/functionEdit.php");
	}
	if($_POST['addUser']=="addUser"){
		include("modules/admin/functionAdd.php");
	}
	if($_POST['editAdmin']=="editAdmin"){
		include("modules/admin/functionEdit.php");
	}
	if($_POST['addGroupDoc']=="addGroupDoc"){
		include("modules/groupDoc/functionAdd.php");
	}
	if($_POST['editGroupDoc']=="editGroupDoc"){
		include("modules/groupDoc/functionEdit.php");
	}
	if($_POST['addStudent']=="addStudent"){
		include("modules/student/functionAdd.php");
	}
	if($_POST['editStudent']=="editStudent"){
		include("modules/student/functionEdit.php");
	}
	if($_POST['themnhomtailieu']=="themnhomtailieu"){
		include("modules/nhomtailieu/thuchien_them.php");
	}
	if($_POST['suanhomtailieu']=="suanhomtailieu"){
		include("modules/nhomtailieu/thuchien_sua.php");
	}
	if($_POST['themtailieu']=="themtailieu"){
		include("modules/tailieu/thuchien_them.php");
	}
	if($_POST['suatailieu']=="suatailieu"){
		include("modules/tailieu/thuchien_sua.php");
	}
?>